#!/bin/ksh

logger -t xcat "Install: setup check what type of kernel should be used (SMP or UP) after first boot"
echo "
if [ -f /etc/sysconfig/CheckCPU ]; then
  if [ \`grep processor /proc/cpuinfo | wc -l\` -le 1 ]
  then
    logger -t xcat \"PostInstall: it's a UP machine, grub.conf needs to be changed\"
    cd /boot/grub/
    mv -f grub.conf grub.conf.ORIG
    sed -e \"s/default=0/default=1/\" grub.conf.ORIG > grub.conf
    rm -f /etc/sysconfig/CheckCPU
    shutdown -r -t 3 now
  else
    logger -t xcat \"PostInstall: it's a SMP machine, nothing needs to be done\"
  fi
  rm -f /etc/sysconfig/CheckCPU
fi
" >>/etc/rc.d/rc.local

echo "CHECKCPU=YES" > /etc/sysconfig/CheckCPU

