#!/bin/ksh
#vallard@us.ibm.com
#(C)IBM Corp
#
set -x
MMSDRFS=mmsdrfs
ARCH=$(uname -i)
KERN=$(uname -r)

if [ -d /post/gpfs31 ]
then
	cd /post/gpfs31
else
	exit
fi

# copy config
if [ -n "$MMSDRFS" ]
then
	if [ -r "$MMSDRFS" ]
	then
		mkdir -p /var/mmfs/gen 2>&1 | logger
		chmod 755 /var/mmfs /var/mmfs/gen 2>&1 | logger
		cp -f $MMSDRFS /var/mmfs/gen/mmsdrfs 2>&1 | logger
	fi
fi

echo $ARCH | perl -pi -e "if(/^i.86$/) {exit 0} else {exit 1}"
if [ "$?" = "0" ]
then
        ARCH=x86
fi

# install rpms
if [ -d /post/gpfs31/$ARCH/base ]
then
	cd /post/gpfs31/$ARCH/base
	rpm -ivh gpfs*.rpm 2>&1 | logger
else
	echo "/post/gpfs31/$ARCH/base does not exist"
	exit
fi

if [ -d /post/gpfs31/$ARCH/update ]
then
	cd /post/gpfs31/$ARCH/update
	rpm -Uvh gpfs*.rpm 2>&1 | logger
fi

# copy portability layer
cd ../bin
cp * /usr/lpp/mmfs/bin/

# copy profile stuff:
cd ../..
cp gpfs.sh gpfs.csh /etc/profile.d


exit 0
