#!/bin/ksh
#egan@us.ibm.com
#(C)IBM Corp
#

. $XCATROOT/lib/functions

RESNAME=$(whatismyres2 $NODE)

if [ "$RESNAME" = "$NODE" ]
then
	RESNAME=""
fi

NODETYPE=$(tabdb $NODETYPETAB $NODE 3)

GROUPS="$(
	egrep "^$NODE( |	|$)" $NODELISTTAB | \
	head -1 | \
	awk '{print $2}' | \
	tr ',' ' '
)"

#for i in $OSVER/$ARCH $OSVER/noarch $ARCH $NODETYPE $RESNAME $GROUPS $NODE $*
for i in $OSVER/$ARCH $OSVER/noarch $ARCH $NODETYPE $GROUPS $NODE $*
do
	newi=$(echo $i | tr '/' '-')
	if [ -d /post/sync/$i ]
	then
		logger -t xcat "Install: copying /post/sync/$i to /"
		if cd /post/sync/$i
		then
			pwd | logger -t xcat
			for j in $(find . -type f -print)
			do
				if [ -r /$j ]
				then
					cp -f /$j /${j}.${newi}.ORIG 2>&1 | logger -t xcat
				fi
			done
			cp -fR * /
#			find . -print | cpio -dump / 2>&1 | logger -t xcat
#			sleep 5
		fi
	else
		logger -t xcat "Install: not syncing from $i"
	fi
done

