#!/bin/ksh
#egan@us.ibm.com
#(C)IBM Corp
#

logger -t xcat "Install: Setup services for $OSVER"
case "$OSVER" in
	rh*)
		chkconfig --del apmd 
		chkconfig --del gpm 
		chkconfig --del kudzu 
		chkconfig --del lpd 
		chkconfig --del pcmcia 
		chkconfig --del linuxconf 
		chkconfig --del sendmail 
		chkconfig --del xfs
		chkconfig --del httpd
		chkconfig --del identd
		chkconfig --del isdn
		chkconfig --del pppoe
		chkconfig --del wine
		chkconfig --del iscsi
		chkconfig --del ip6tables
		chkconfig --del ipchains
		chkconfig --del rhnsd
		chkconfig --del rawdevices
		chkconfig --del cups
		chkconfig --del hpoj
		chkconfig --del mdmonitor
		chkconfig --del mdmpd
		chkconfig --del bluetooth
		chkconfig sgi_fam off
		chkconfig --level 345 ntpd on
		chkconfig --level 345 sshd on
		chkconfig --level 345 ext_sshd on
		chkconfig --level 345 snmpd on
		chkconfig --level 345 autofs on
		;;
	sles[89]|suse8*|suse9*)
		chkconfig -a nfs
		chkconfig -a xntpd
		;;
esac

