#!/bin/ksh

logger -t xcat "Install: setup GPFS on node"

echo "

SHORTHOSTNAME=\$(echo \$HOSTNAME | awk -F. '{print \$1}')

if [ -n \"\`ssh storage009 mmlscluster | grep -w \$SHORTHOSTNAME\`\" ]; then
  scp storage009:/var/mmfs/gen/mmsdrfs /var/mmfs/gen/
fi
                                                                                          
if [ -n \"\`ssh storage011 mmlscluster | grep -w \$SHORTHOSTNAME\`\" ]; then
  scp storage011:/var/mmfs/gen/mmsdrfs /var/mmfs/gen/
fi
                                                                                          
if [ -n \"\`ssh storage016 mmlscluster | grep -w \$SHORTHOSTNAME\`\" ]; then
  scp storage016:/var/mmfs/gen/mmsdrfs /var/mmfs/gen/
fi

sleep 5

/usr/lpp/mmfs/bin/mmstartup
                                                                                          
" >>/etc/rc.d/rc.local

