#!/bin/ksh
#
# Install additional rpms
#
###############################################################################
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version
# 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

logger -t xcat "Install: vmware-install"

if [ -r /etc/vmware1 ]; then
	cd /post/otherrpms/VMware/
	rpm -ihv *.rpm 2>&1 | logger -t xcat
	cd /
	rm -rf /etc/vmware /etc/vmware1
	cp -r /post/otherrpms/VMware/vmware /etc/vmware
	/bin/chmod 755 /etc/vmware
	logger -t xcat "Install: injecting vmware-config.pl --d into rc.local"
	echo "vmware-config.pl --d" >> /etc/rc.local
	echo "/sbin/chkconfig --levels 2345 vmware on" >> /etc/rc.local
fi
