#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# $1 = flag for persistence

if [ -n "$1" ]; then
   persist=1
fi


# this is non persistent
sysctl -w net.inet.ip.fw.enable=1

# could also have used
# ipfw enable firewall

if [ -n "$persist" ]; then
   touch /etc/ipfilter/ipfwstate-on
   chmod 444 /etc/ipfilter/ipfwstate-on
fi


