#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



/usr/bin/killall loginwindow


#        osascript -e 'tell application \"System Events\"

# for i in `/usr/bin/users | sed 's/root//'`
# do
#    result=`ps -U $i | grep Finder | grep -v grep`
#    if [ "$result" != "" ]; then
# echo user is $i
# #       su - $i -c "osascript -e \'tell application \"Finder\"
# #       do shell script \"kill -9 \`ps -Axjc | grep loginwindow | cut -c 12-15\`\"
# #         end tell\' "
# #      su - $i -c "osascript -e \'tell application \"Finder\" to quit\'"
#       su - $i -c "osascript -e \'tell application \"System Events\" to log out\'"
# #        key down shift
# #        key down option
# #        key down command
# #        keystroke \"q\"
# #        key up shift
# #        key up option
# #        key up command
# #        end tell' "
#    fi
# done


#      su - $i -c "osascript -e \'tell application \"Finder\" to quit\'"
#        key down shift
#        key down option
#        key down command
#        keystroke \"q\"
#        key up shift
#        key up option
#        key up command
#        end tell' "
