#!/bin/bash

# i.e. 'password_reset 899112222 password'
USERNAME="$1"
PASSWORD="$2"

if [[ $UID -ne 0 ]]; then
   echo " sorry, must be root to run this script"
   exit 1
fi

RESULT=$(dscl . list /Users | grep $USERNAME)
if [ -z "$RESULT" ]; then
  echo " user account: \"$USERNAME\" does not exist"
  exit 1
fi

dscl . -passwd /Users/$USERNAME "$PASSWORD"

echo "$USERNAME password reset on `date`"

