#!/bin/ksh

logger -t xcat "Install: setup iptables"
cp /etc/sysconfig/iptables /etc/sysconfig/iptables.ORIG
echo "# Firewall configuration written by redhat-config-securitylevel" > /etc/sysconfig/iptables
echo "# Manual customization of this file is not recommended." >> /etc/sysconfig/iptables
echo "*filter" >> /etc/sysconfig/iptables
echo ":INPUT ACCEPT [0:0]" >> /etc/sysconfig/iptables
echo ":FORWARD ACCEPT [0:0]" >> /etc/sysconfig/iptables
echo ":OUTPUT ACCEPT [0:0]" >> /etc/sysconfig/iptables
echo ":RH-Firewall-1-INPUT - [0:0]" >> /etc/sysconfig/iptables
echo "-A INPUT -j RH-Firewall-1-INPUT" >> /etc/sysconfig/iptables
echo "-A FORWARD -j RH-Firewall-1-INPUT" >> /etc/sysconfig/iptables
echo "-A RH-Firewall-1-INPUT -i lo -j ACCEPT" >> /etc/sysconfig/iptables
echo "-A RH-Firewall-1-INPUT -i eth0 -j ACCEPT" >> /etc/sysconfig/iptables
echo "-A RH-Firewall-1-INPUT -p icmp --icmp-type any -j ACCEPT" >> /etc/sysconfig/iptables
echo "-A RH-Firewall-1-INPUT -p 50 -j ACCEPT" >> /etc/sysconfig/iptables
echo "-A RH-Firewall-1-INPUT -p 51 -j ACCEPT" >> /etc/sysconfig/iptables
echo "-A RH-Firewall-1-INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT" >> /etc/sysconfig/iptables
echo "-A RH-Firewall-1-INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT" >> /etc/sysconfig/iptables
echo "-A RH-Firewall-1-INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT" >> /etc/sysconfig/iptables
echo "-A RH-Firewall-1-INPUT -m state --state NEW -m tcp -p tcp --dport 8080 -j ACCEPT" >> /etc/sysconfig/iptables
echo "-A RH-Firewall-1-INPUT -j REJECT --reject-with icmp-host-prohibited" >> /etc/sysconfig/iptables
echo "COMMIT" >> /etc/sysconfig/iptables
