#!/bin/ksh
#egan@us.ibm.com
#(C)IBM Corp
#

. $XCATROOT/lib/functions

echo "$RSHC" | grep "ssh" >/dev/null 2>&1
if [ "$?" = "0" ]
then
	logger -t xcat "Install: Running makesshgkh on the server"

	service sshd start
	ssh $MASTER $XCATROOT/sbin/makesshgkh $NODE
	service sshd stop
fi

if [[ $(ls /root/.ssh/ | grep ORIG | wc -l) != "0" ]]
then
  rm -f /root/.ssh/*ORIG
else
  rm -f /root/.ssh/id_rsa
  rm -f /root/.ssh/id_rsa.pub
  rm -f /root/.ssh/config
fi

exit 0
