#!/bin/ksh
#vallard@us.ibm.com
#(C)IBM Corp
#
ARCH=$(uname -i)
KERN=$(uname -r)

NODEPS=""
for i in $*
do
    case "$i" in
        nodeps)
            NODEPS="--nodeps"
            ;;
    esac
done


echo $ARCH | perl -pi -e "if(/^i.86$/) {exit 0} else {exit 1}"
if [ "$?" = "0" ]
then
	ARCH=x86
fi

# install RPMs with --nodeps option
if [ -d /post/openafs/$OSVER/$ARCH/ ]
then
	logger -t xcat "Install: OpenAFS RPMs"
	cd /post/openafs/$OSVER/$ARCH/
	rpm -iv --nodeps *.rpm 2>&1 | logger -t xcat
else
	echo "/post/openafs/$OSVER/$ARCH/ does not exist"
	exit
fi

exit 0

# install rpms based on type of kernel (UP vs. SMP)
#if [ -z `echo $KERN | grep "smp"` ]
if [ `grep processor /proc/cpuinfo | wc -l` -le 1 ]
then
  if [ -d /post/openafs/$OSVER/$ARCH/up ]
  then
	logger -t xcat "Install: OpenAFS RPMs for UP kernel ($KERN)"
	cd /post/openafs/$OSVER/$ARCH/up
	rpm -ivh $NODEPS *.rpm 2>&1 | logger -t xcat
  else
	echo "/post/openafs/$OSVER/$ARCH/up does not exist"
	exit
  fi
else
  if [ -d /post/openafs/$OSVER/$ARCH/smp ]
  then
i	logger -t xcat "Install: OpenAFS RPMs for SMP kernel ($KERN)"
	cd /post/openafs/$OSVER/$ARCH/smp
	rpm -ivh $NODEPS *.rpm 2>&1 | logger -t xcat
  else
	echo "/post/openafs/$OSVER/$ARCH/smp does not exist"
	exit
  fi
fi

exit 0
